### ISSUE TITLE
[PO-02] Design da tela de login

### ISSUE THREAD

**Issue by caio11pessoa** [Luksdantas/PredictionOnline#1]
- [x] Criar imagem de Fundo
- [x] Definir local onde ficará a logo do jogo
- [x] Definir logo do jogo
- [x] Criar Bloco onde ficará as entradas
- [x]  Adicionar texto "NICKNAME" Com as devidas imagens centralizada encima da caixa
- [x] Adicionar dentro do bloco a caixa de texto do login
- [x] Definir dentro do bloco o botão START
- [x] Definir dentro do bloco o botão HELP

**Comment by jamile-loureiro** [comment]
Deu bom demais, é nós na próxima issue!
