### ISSUE TITLE
[PO-10] Padronização das páginas, refatoração e linkagens

### ISSUE THREAD

**Issue by caio11pessoa** [Luksdantas/PredictionOnline#17]
- [x] Organizar os arquivos nas pastas;
- [x] Estudar mais CSS;
- [x] Fazer linkagem entre as páginas;

**Comment by Anilton-magalhaes** [comment]
Seria interessante mover esses arquivos na dev pra uma pasta especifica "web" e depois padronizar na branch especifica, dando pull request da branch pra dev em um merge no final?
