### ISSUE TITLE
[PO-16]Implementar a tela de fim apresentando o Ranking de 4 Jogador Mockados

### ISSUE THREAD

**Issue by caio11pessoa** [Luksdantas/PredictionOnline#28]
- [x] Criar branch da issue

- [x] Com base nos 4 arquivos .json fornecidos por Anilton, fazer com que a tela de fim seja capaz de exibir os dados que ele contém

- [x] Dar pull request quando os demais itens estiverem concluídos

**Comment by Anilton-magalhaes** [comment]
Lucas está refazendo as telas, portanto acho que seria interessante falar com ele pra conseguir a tela de fim mais recente
