### ISSUE TITLE
[PO-07] Programar o layout da Tela de Login

### ISSUE THREAD

**Issue by Luksdantas** [Luksdantas/PredictionOnline#6]
- [x] Definir background com a respectiva imagem;
- [x] Criar contêiner onde estará o conteúdo da imagem;
- [x] Definir tamanho da tela como 1080/1920;
- [x] Posicionar nome do jogo no local indicado pelo protótipo;
- [x] Posicionar caixa contendo os botões e entradas no local indicado no protótipo;
- [x] Adicionar botão Help no local indicado pelo protótipo;

**Comment by jamile-loureiro** [comment]
Concluído!
